# Set Airflow and Python version
ARG AIRFLOW_VERSION=2.3.2
ARG PYTHON_VERSION=3.7

# Airflow image
FROM apache/airflow:${AIRFLOW_VERSION}-python${PYTHON_VERSION}

USER airflow

COPY assets/requirements.txt .

RUN pip3 install -r requirements.txt
