
x-airflow-common:
  &airflow-common
  build:
    context: "."
    dockerfile: "Dockerfile"
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres:5432/airflow_metadata_db
    - AIRFLOW__DATABASE__LOAD_DEFAULT_CONNECTIONS=False
    - AIRFLOW__LOGGING__LOGGING_LEVEL=INFO
    - _AIRFLOW_DB_UPGRADE=True
    - _AIRFLOW_WWW_USER_CREATE=True
    - _AIRFLOW_WWW_USER_USERNAME=airflow
    - _AIRFLOW_WWW_USER_PASSWORD=airflow
  volumes:
    - ./dags:/opt/airflow/dags
    - ./airflow-utils/logs:/opt/airflow/logs
    - ./airflow-utils/plugins:/opt/airflow/plugins
    - ./airflow-utils/airflow.cfg:/opt/airlfow/airflow.cfg
  depends_on:
    - postgres
  networks:
    - shared-network

services:
###########################
## AIRFLOW WEBSERVER
  airflow-webserver:
    << : *airflow-common
    command: airflow webserver
    ports:
      - 8085:8080
    container_name: airflow_webserver
    restart: always

###########################
## AIRFLOW SCHEDULER
  airflow-scheduler:
    << : *airflow-common
    command: airflow scheduler
    container_name: airflow_scheduler
    restart: always

# POSTGRES DB
##########################
  postgres:
    image: debezium/postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_DB=airflow_metadata_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5435:5432"
    volumes:
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - shared-network
###########################
## SQLPAD
  sqlpad:
    image: sqlpad/sqlpad:latest
    container_name: sqlpad
    ports:
      - "3000:3000"
    environment:
      SQLPAD_ADMIN: admin@sqlpad.com
      SQLPAD_ADMIN_PASSWORD: admin
      SQLPAD_CONNECTIONS__pgconn__name: AnalytycsDB
      SQLPAD_CONNECTIONS__pgconn__driver: postgres
      SQLPAD_CONNECTIONS__pgconn__host: postgres
      SQLPAD_CONNECTIONS__pgconn__database: analytics_db
      SQLPAD_CONNECTIONS__pgconn__username: postgres
      SQLPAD_CONNECTIONS__pgconn__password: postgres
      SQLPAD_CONNECTIONS__pgconn__idleTimeoutSeconds: 60
    depends_on:
      - postgres
    networks:
      - shared-network
###########################
## NETWORKS
networks:
  shared-network:
    driver: bridge
